name: shopify
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  intl: ^0.16.1
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+1
  firebase_database: ^3.1.1
  get: ^4.1.2
  frideos: ^1.0.1
  prefs: ^3.0.0
  url_launcher: ^5.7.5
  flutter_linkify: ^4.0.2
  mailto: ^1.1.0
  geocoding: ^1.0.5
  geolocator: ^6.2.1
  geocoder: ^0.2.1
  google_maps_flutter: ^2.0.2
  location: ^3.0.0
  flutter_rating_bar: ^4.0.0
  app_settings: ^4.1.0
  flutter_dialogflow: ^0.1.2
  bubble: ^1.2.1
  adaptive_theme: ^1.1.0
  dots_indicator: ^2.0.0
  introduction_screen: ^2.1.0
  awesome_dialog: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
  - assets/images/product-placeholder.png
  - assets/images/shop.png
  - assets/images/shop1.png
  - assets/images/shop2.png
  - assets/images/color.png
  - assets/images/color2.png
  - assets/credentials.json
  - assets/credentials1.json
  - assets/images/onboard1.jpg
  - assets/images/onboard2.jpg
  - assets/images/onboard3.jpg
  - assets/images/onboard4.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 900
    - family: Quicksand 
      fonts:      
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 900
    - family: TrainOne
      fonts:      
        - asset: assets/fonts/TrainOne-Regular.ttf
    - family: Lobster
      fonts:      
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Raleway
      fonts:      
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Pangolin
      fonts:      
        - asset: assets/fonts/Pangolin-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 900
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
